"""
Django settings for apk_detector project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Suppress TensorFlow C++ logs before TF is imported anywhere.
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
# Disable oneDNN custom ops to prevent the early C++ absl startup messages
# that TF_CPP_MIN_LOG_LEVEL cannot catch (they are written before absl::InitializeLog).
os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"
# Suppress absl (used by TF/Keras internally).
os.environ["ABSL_MIN_LOG_LEVEL"] = "3"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#(s#a25c@e)ws*_m^c6b-%d@i=%d6j8q40t6se+b!)&bg0v)5#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["https://app-production-9178.up.railway.app"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pipeline',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apk_detector.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apk_detector.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# WhiteNoise: serve files via finders even if collectstatic hasn't run yet.
WHITENOISE_USE_FINDERS = True
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # Compress static files when collectstatic runs; no manifest required,
    # so the app works even if collectstatic hasn't been run yet.
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Allow large APK uploads (up to 100 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 104_857_600
FILE_UPLOAD_MAX_MEMORY_SIZE  = 104_857_600

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Logging ────────────────────────────────────────────────────────────────────
# Keep only WARNING+ in production to avoid Railway's rate-limit.
# Libraries like TensorFlow, androguard, and absl are extremely chatty at INFO.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        # Explicit WARNING floor so that child-logger records that propagate
        # up cannot bypass the parent logger's ERROR gate on this handler.
        "console": {
            "class": "logging.StreamHandler",
            "level": "WARNING",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        # Django request errors (500s) still reach the console.
        "django.request":           {"handlers": ["console"], "level": "ERROR", "propagate": False},
        # Silence the heaviest offenders — parent + key child loggers.
        "tensorflow":               {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "keras":                    {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "absl":                     {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "androguard":               {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "androguard.core":          {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "androguard.misc":          {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "androguard.core.apk":      {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "androguard.core.bytecodes":{"handlers": ["console"], "level": "ERROR", "propagate": False},
        "androguard.decompile":     {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "pipeline":                 {"handlers": ["console"], "level": "WARNING", "propagate": False},
    },
}
