# Generated by Django 6.0.5 on 2026-05-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_hash', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, choices=[('adware', 'Adware'), ('banking', 'Banking'), ('benign', 'Benign'), ('riskware', 'Riskware'), ('sms', 'SMS Malware'), ('unknown', 'Unknown')], max_length=32)),
                ('image', models.ImageField(upload_to='results/')),
                ('sequence_preview', models.TextField()),
                ('tabular_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
